version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_music_lib_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "4000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: